### ISSUE TITLE
Usability issue in Chrome: Page hierarchy shows only a few pages after viewing a topic

### ISSUE THREAD

**Issue by thejeed** [orientechnologies/orientdb-docs#1]
After clicking on a topic in the page hierarchy on the left, this hierarchy changes in a way that I can't see all the topics anymore:
![image](https://cloud.githubusercontent.com/assets/5215534/6651119/24b0a4b4-ca35-11e4-91de-8b7cd5ba6504.png)

Using the back-button of the browser results in the content changing to the last viewed page, but the hierarchy stays broken.

Environment:
Windows 8.1 x64, Google Chrome 41.0.2272.89 m

But it works in Firefox 34.0.5 or in the Chromium Browser under Linux Mint

**Comment by santo-it** [comment]
Hi,

Thanks for opening this issue and apologize for late reply

I think this is not happening anymore with latest versions of the doc

I'm closing this issue now. If you feel this is still current, please feel free to reopen

Thanks again!
