### ISSUE TITLE
Reroute old links to new docs.

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb-docs#107]
I've noticed that old links in Google lead to old docs. This isn't quite clear and people then get old information and then end up asking questions, like this one.

https://groups.google.com/forum/#!topic/orient-database/F6IXBzUphcc%5B1-25%5D

If possible, it probably be better to redirect to the newest version of the docs.

Scott

**Comment by santo-it** [comment]
Hi, thanks for opening this issue

See also Issue #101

**Comment by smolinari** [comment]
Closing since this is a dupe. I didn't realize I had posted this issue earlier. LOL! 😊 

Scott
