### ISSUE TITLE
Example Query throws parsing error

### ISSUE THREAD

**Issue by nathanhere** [orientechnologies/orientdb-docs#129]
The example query on line 152 of SQL-Traverse.md is missing a closing parenthesis. However, even with the parenthesis correction, the query throws a parsing error using the pyOrient driver.

**Comment by luigidellaquila** [comment]
Hi @nathanhere 

good catch, I'm changing that page, it contains a lot of old stuff

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Fixed and pushed a fix on the repo.

The fix will be in the official docs in a few hours

Thanks

Luigi

**Comment by nathanhere** [comment]
Awesome. I've been hanging around the docs for the past few weeks, hope you don't mind more upcoming pull requests :)

**Comment by luigidellaquila** [comment]
Absolutely! Both suggestions and pull requests are always welcome :-)

Thanks

Luigi
