### ISSUE TITLE
2.1 doc pdf link broken

### ISSUE THREAD

**Issue by zhuobao** [orientechnologies/orientdb-docs#152]
the latest version (2.1) doc pdf link is broken

**Comment by santo-it** [comment]
Hi,

Thanks for opening this issue

The pdf link included in the page http://orientdb.com/docs/2.1.x/ seems to work now (the link to the pdf is http://orientdb.com/docs/2.1.x/OrientDB-Manual.pdf)

I'm closing this issue now. Please feel free to reopen if you feel this is still broken

Many thanks,
