### ISSUE TITLE
Teleporter configuration is incomplete

### ISSUE THREAD

**Issue by Koc** [orientechnologies/orientdb-docs#168]
1. https://github.com/orientechnologies/orientdb-docs/blob/master/Teleporter-Import-Configuration.md this chapter is invisible inside docs http://orientdb.com/docs/last/Teleporter-Home.html
2. There is a lack of information how to use teleporter as replication tool. Should i use specific settings, cron or supervisord or smth else. And how to deal with deletions inside master database?
3. Last version is 2.2, but http://orientdb.com/docs/2.2/Teleporter-Home.html is not equals to http://orientdb.com/docs/last/Teleporter-Home.html, some information is missing on 2.2 version of docs
4. Please provide examples how to use remote target database with login and password instead of plocal

**Comment by G4br13l3** [comment]
1. You are right, doc is outdated, now we are working to make the two documentations aligned. Meanwhile you can refer to orientdb-docs.
2. Look here:

https://github.com/orientechnologies/orientdb-docs/blob/master/Teleporter-Sequential-Executions-and-One-Way-Synchronizer.md

Teleporter works as a one-way synchronizer, so  when you run it you will have a full synch regarding the schema, and a delete-less synch regarding the records. So adds and updates performed in your source db will be propagated, but deletes will not. 
3. As said at the point 1. we are working to align the doc versions, thank you very much for your notice!
4. You have simply to use a remote URL according to the orientdb doc:
   
./oteleporter.sh -jdriver postgresql -jurl jdbc:postgresql://localhost:5432/testdb 
                -juser username -jpasswd password -ourl **remote:localhost/testdb**

**Comment by G4br13l3** [comment]
The documentation is now updated, so I'm closing this issue. Feel free to reopen it if you run into similar lacks again.
Thanks
