### ISSUE TITLE
URLs with anchors don't go to the achored section of the docs

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb-docs#173]
For example,

http://orientdb.com/docs/last/Tutorial-Using-schema-with-graphs.html#using-in-and-out-constraints-on-edges

This URL should scroll down or position the page to show the section "Using in and out constraints" at the top of the page. The anchor doesn't seem to work. It looks like the anchor is removed from the URL by the server.

Scott

**Comment by mattall** [comment]
I see this problem too. When I click the link I'm taken to the intended section of the page, but then a moment later the I'm brought to the top of the page.

Matt

**Comment by robfrank** [comment]
We had some problem with anchors that now are solved.
