### ISSUE TITLE
I can not use this delete function.

### ISSUE THREAD

**Issue by reggieroby** [orientechnologies/orientdb-docs#192]
the docs provided here: http://orientdb.com/docs/2.2.x/OrientJS-Query-Delete.html

function I am using: 
`DB.delete('VERTEX').where('@rid = '+vID).one;`

I get this error
`Unhandled rejection OrientDB.RequestError: Error on parsing command at position #0: Encountered " <WHERE> "WHERE "" at
 line 1, column 15.
Was expecting one of:
    <FROM> ...
    <TO> ...
    <VALUES> ...
    <SET> ...
    <ADD> ...
    <PUT> ...
    <MERGE> ...
    <CONTENT> ...
    <REMOVE> ...
    <ORDER> ...
    <GROUP> ...
    <OFFSET> ...
    <RECORD> ...
    <LUCENE> ...
    <NEAR> ...
    <WITHIN> ...
    <EXCEPTION> ...`

**Comment by luigidellaquila** [comment]
Hi @reggieroby 

Could you please specify the value of vID?

Thanks

Luigi

**Comment by reggieroby** [comment]
#16:0

**Comment by maggiolo00** [comment]
@reggieroby 

i've updated the docs.

If you use db.delete with vertex you should specify the vertex class as well.

```js
DB.delete('VERTEX','YourClass').where('@rid = '+vID)
.one()
.then(function(count){
 console.log(count)
});
```
https://github.com/orientechnologies/orientdb-docs/blob/2.2.x/OrientJS-Query-Delete.md
