### ISSUE TITLE
Incorrect naming of the arguments in various functions 

### ISSUE THREAD

**Issue by Briksins** [orientechnologies/orientdb-docs#2]
Hi

So far I had a chance to touch "OServerAdmin" class which has incorrectly named arguments in API documentation:
http://www.orientechnologies.com/javadoc/latest/index.html?com/orientechnologies/orient/client/remote/OServerAdmin.html 

For example:
deleteDatabase(String storageType)
dropDatabase(String storageType)
existsDatabase(String storageType)
freezeDatabase(String storageType)
releaseCluster(int clusterId, String storageType)
releaseDatabase(String storageType) 

all of those should be: databaseName instead of storageType

It is not even clear what is storageType? was it mean iDatabaseType? or iStorageMode?
iDatabaseType - could be "document" or "graph"
iStorageMode - "plocal" or "memory"

anyway it doesnt matter what was mean under storageType but you definatly cannot dropDatabase(String storageType)
by it storage type as there can be multiple databases of the same storageType. it should be database name

**Comment by lvca** [comment]
I've improved Javadocs. However that `storageType` is the kind of storage between `plocal` and `memory`.
