### ISSUE TITLE
ODB Download Link

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-docs#236]
Discussed internally, opening an issue for reference

It's important that we have a single link that points to the latest ODB version, or a variable in gitbook that we can update each time we make a release so that the download links included in the doc will always point to the correct ODB archive

Some example of what we have right now:

1. In http://orientdb.com/docs/master/Import-the-Database-of-Beers.html#install-orientdb
>- $ curl "http://orientdb.com/download.php?email=unknown@unknown.com&file=orientdb-community-2.2.8.zip&os=multi" > orientdb-community-2.2.8.zip

2. In http://orientdb.com/docs/master/Tutorial-Installation.html#binary-installation
> - $ wget https://orientdb.com/download.php?file=orientdb-community-2.2.0.tar.gz

@robfrank FYI

**Comment by robfrank** [comment]
We can use variables defined inside book.json:
https://github.com/orientechnologies/orientdb-docs/commit/5ef23e1ce970c8e184f6b11d14ee18c40e3372a0#diff-609ea0a435d067757e821e3114b666a1

**Comment by santo-it** [comment]
Thanks @robfrank for working on this. Well done

As second step, I think we'll now benefit from changing a bit the download command. In fact,  

wget http://mkt.orientdb.com/CE-2213-OSX

does not seems to work. The following one, where the -O is used, works instead:

wget http://mkt.orientdb.com/CE-2213-OSX -O orientdb-community-2.2.13.tar.gz

We could write that orientdb-community-2.2.13.tar.gz as orientdb-community-{{ book.download_version }}.tar.gz

or find a similar solution. WDYT?

Thanks,

**Comment by robfrank** [comment]
Yes, I think that the _version_ could be used almost everywhere, so a variable currentVersion should be enough

**Comment by santo-it** [comment]
1 & 2 have been fixed now

Removing the label bug as major problems have been fixed and adding the label enhancement. Keeping this issue open so that we can have a chance to identify and update other parts of the doc that include old download links

**Comment by santo-it** [comment]
Fixed a few pages and updated the readme-github page, to describe how to cite variables.

@robfrank hi, when possible, please check my changes in the spatial plugin page. If they are okay, we can consider to backport them into 2.2.

Thanks,

**Comment by santo-it** [comment]
@robfrank FYI: I have backported the changes in the spatial plugin page in 2.2 now
