### ISSUE TITLE
link to Schema API on http://orientdb.com/docs/last/orientdb.wiki/Object-Database.html dead

### ISSUE THREAD

**Issue by krichter722** [orientechnologies/orientdb-docs#25]

**Comment by lvca** [comment]
Sorry I can't find it. What paragraph?

**Comment by krichter722** [comment]
right under "Work in schema-full mode"

**Comment by lvca** [comment]
Found it: the right page is http://orientdb.com/docs/last/Object-Database.html and not http://orientdb.com/docs/last/orientdb.wiki/Object-Database.html. That page is old. How did you arrive there?

**Comment by krichter722** [comment]
It's the first hint in google for the query `orientdb object api` (can't check google.com because of google's everlasting nonsense redirection), see https://www.google.de/?gws_rd=ssl#q=orientdb+object+api for details.

Can you add a deprecation banner or take it off the air?

**Comment by lvca** [comment]
Fixed, thanks for reporting.

**Comment by krichter722** [comment]
So, you put http://orientdb.com/docs/last/orientdb.wiki/... off the air, right? http://orientdb.com/docs/2.0/orientdb.wiki/... is still available and now the first hit in google and possibly other search engines.

**Comment by lvca** [comment]
I changed 2.0, try to reload the page (click on "Object API" on the left side menu)

**Comment by krichter722** [comment]
> I changed 2.0, try to reload the page (click on "Object API" on the left side menu)

I see the fix and it works, thanks. My point is that it doesn't cover all cases where the dead link can be reached. The "use case" `google query for "orientdb object api"` -> http://orientdb.com/docs/2.0/orientdb.wiki/Object-Database.html -> Schema API link still leads to a 404 page.

Where can I find the difference between http://orientdb.com/docs/[version]/... and http://orientdb.com/docs/[version]/orientdb.wiki/... explained?

**Comment by lvca** [comment]
If you open that page from another browser you'll see the page is updated. So was cached in your case. About that difference with 2.0 we started to have a flat directory of documentation, so the "orientdb.wiki" is obsolete. Was there to avoid 404 at the beginning.

**Comment by krichter722** [comment]
And I thought that Mozilla would have fixed their 10 year old bugs regarding cache cleaning when requested by the user by now - silly me. It works in `midori` - and I guess in firefox as well after the cache has been invalidated which apparently is beyond user control.
