### ISSUE TITLE
ODB 3.0 Docs - DELETE EDGE 

### ISSUE THREAD

**Issue by SpareShade** [orientechnologies/orientdb-docs#285]
Hi, 
tried to find this to edit in docs (https://github.com/orientechnologies/orientdb-docs/edit/master/release/Release-3.0.0.md) but the link is not working.

# Changes in the DELETE EDGE statement

you suggest as edge class is mandatory in ODB 3 to use (If you don't want to get bored in remembering your class hierarchy you can simply specify the 'E' Edge Class.)

```javascript
delete edge E where out=#9:0 and in=#10:1
```

This is rather **dangerous** suggestion as there might be different edges with exactly same in/out vertices. Doing so would delete all those edges.

**Comment by santo-it** [comment]
Hi @SpareShade ,

Many thanks for opening this issue. The "edit this page" link should work now.
I have pushed a commit that fixes the issue - the fix will be incorporated as soon as possible in the next build.

For now you can check the fixed page directly in github here: https://github.com/orientechnologies/orientdb-docs/blob/3.0.x/release/3.0/SQL-Changes.md

Closing.

Thanks again,
