### ISSUE TITLE
3.x branch - build is broken

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-docs#287]
error: error while parsing page "java/Java-Ref-OElement-getProperty.md": 

YAMLException: unexpected end of the stream within a single quoted scalar at line 3, column 1

http://helios.orientdb.com/job/orientdb-docs-multibranch/job/3.0.x/53/console

**Comment by kennethpjdyer** [comment]
That should fix the YaML.  I'll watch to the builds to make sure there's nothing else in there.

**Comment by kennethpjdyer** [comment]
It's building successfully again.
