### ISSUE TITLE
Please mention the #orientdb on freenode in the docs

### ISSUE THREAD

**Issue by oren** [orientechnologies/orientdb-docs#30]
I noticed nothing mentioned here: http://orientdb.com/active-user-community/
I would also add it the the main docs page: http://orientdb.com/docs/last/

**Comment by lvca** [comment]
Do you have a http URL for it?

**Comment by oren** [comment]
This is the freenode web interface:
http://webchat.freenode.net/?channels=orientdb

Here are other clients:
* **Web-based, Linux, Mac, Windows** - https://en.wikipedia.org/wiki/Comparison_of_Internet_Relay_Chat_cl
* **Android** - http://www.reddit.com/r/irc/comments/1ogoy4/suggested_android_irc_clients/
* **iOS** - http://www.reddit.com/r/irc/comments/18a8ll/best_irc_for_an_iphone_user/

I use [weechat](https://weechat.org/about/features), text-based IRC client running on a $5 Digital Ocean so I am connected 24/7.

**Comment by lvca** [comment]
Done. Thanks.

**Comment by oren** [comment]
thanks
