### ISSUE TITLE
Getting started key value use case - "Impossible to create an index"

### ISSUE THREAD

**Issue by Sygyzmundovych** [orientechnologies/orientdb-docs#334]
I'm trying to go through http://orientdb.com/docs/3.0.x/gettingstarted/Key-Value-use-case.html#create-a-new-index tutorial, but in that step receiving an error

```sh
C:\Tools\curl-7.61.0-win64-mingw\bin>curl --basic -u admin:admin localhost:2480/command/test/sql -d "create index mainbucket UNIQUE"
```

```json
{
  "errors": [
    {
      "reason": 500,
      "code": 500,
      "content": "com.orientechnologies.orient.core.exception.ODatabaseException: Impossible to create an index without specify class and property name nor key types: CREATE INDEX mainbucket UNIQUE\u000d\u000a\u0009DB name=\"test\""
    }
  ]
}
```

The same error if executed from the console.

I am new to OrientDB, so unfortunately do not know yet what complete CREATE INDEX syntax should be in this case.

**Comment by luigidellaquila** [comment]
Hi @Sygyzmundovych 

i just checked the tutorial, it was outdated in fact (it was probably written before v 2.0 and never updated, in V 3.0 we changed some defaults, so it didn't work).

To make it work, you have to do the following:

- declare the key type for the index (using STRING here):
```
> curl --basic -u admin:admin localhost:2480/command/demo/sql -d "create index mainbucket UNIQUE STRING"
```
- declare the class for the document you are inserting (I'm using `'@class':'V'` in the example here, just to avoid to create new classes)

```
> curl --basic -u admin:admin -X PUT localhost:2480/index/demo/mainbucket/jay -d "{'@class': 'V', 'name':'Jay','surname':'Miner'}"
```

I also updated the tutorial, it will be available in a few hours

Thanks

Luigi
