### ISSUE TITLE
3.0 - spatial support confusion

### ISSUE THREAD

**Issue by myflowpl** [orientechnologies/orientdb-docs#339]
1 - In docs `http://orientdb.com/docs/3.0.x/indexing/Spatial-Index.html` it says you have to download the plugin manually from the maven repostitory, but the maven repository link is broken, and last version available there is for 3.0.0RC2 
**so there is no possibility to download the spatial plugin manually for version 3.0.0+**

2 - here the docs say there is special package with spatial included `http://orientdb.com/docs/3.0.x/release/3.0/Available-Packages.html#`
but when you look and compere at the links, there are only two packages:

CE (orientdb-community-3.0.10.tar.gz)
CE-TP2 (orientdb-community-tp2-3.0.10.tar.gz)
links goes to: 
`https://s3.us-east-2.amazonaws.com/orientdb3/releases/3.0.10/orientdb-3.0.10.tar.gz`

CE-TP3 (orientdb-community-tp3-3.0.10.tar.gz)
CE-spatial-TP3 (orientdb-community-spatial-3.0.10.tar.gz)
links goes to:
`https://s3.us-east-2.amazonaws.com/orientdb3/releases/3.0.10/orientdb-tp3-3.0.10.tar.gz`

also it looks like the names changed from `orientdb-community-3.0.0.tar.gz` na `orientdb-3.0.0.tar.gz`

**Truth is, when you download both of the package and compere it, both packages has included spatial plugin.**

3 - there are two download sites for community edition
`https://orientdb.com/download-2/`
`https://orientdb.org/download`
none of them mentions the package with spatial 

**looks like v 3.0 has spatial plugin added by default, but docs are misleading**

**Comment by luigidellaquila** [comment]
Hi @myflowpl 

Yes, the docs are outdated, in v 3.0 the plugin is shipped in the default distribution.
I'm going to fix them

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Fixed, thanks!

Luigi

**Comment by myflowpl** [comment]
looks good now :)

but have two more confusing places:
this docs about available packages is still referencing special spatial package:
[http://orientdb.com/docs/3.0.x/release/3.0/Available-Packages.html](http://orientdb.com/docs/3.0.x/release/3.0/Available-Packages.html)

and on this page:[https://orientdb.com/download-2/]( https://orientdb.com/download-2/)
the link to `OrientDB with Gremlin Server - tar.gz` is still referencing version 3.0.10 instead of 3.0.11

BTW
do you need two pages for download community version ?
https://orientdb.com/download-2/
https://orientdb.org/download
?

**Comment by luigidellaquila** [comment]
Hi @myflowpl 

Thank you very much for double-checking, I'm fixing the docs and the download page now (I just missed it while updating it after the release).

The .org website is a new initiative and is still ramping up, probably in the long term we will have only a single download page

Thanks

Luigi
