### ISSUE TITLE
Documentation of OrientDB for Version 3.x is totally missing 

### ISSUE THREAD

**Issue by akshattandon** [orientechnologies/orientdb-docs#341]
Documentation of OrientDB for Version 3.x is totally missing 
https://orientdb.com/docs/3.0.x/programs/Server-Startup-Programs.html
https://orientdb.com/docs/3.0.x/programs/Client-Programs.html
https://orientdb.com/docs/3.0.x/programs/Administrative-Utility-Programs.html .....

And the list is quite big.

Is there any way we can get the same updated otherwise the project doesn't look Professional 

Thanks 
Akshat

**Comment by luigidellaquila** [comment]
Hi @akshattandon 

I fixed the links you mentioned, I'll do a complete check, but if you have other links to suggest it will help for sure

Thanks

Luigi

**Comment by akshattandon** [comment]
Great work @luigidellaquila
