### ISSUE TITLE
Update Installation to list mandatory files or changes

### ISSUE THREAD

**Issue by lnryan** [orientechnologies/orientdb-docs#343]
The organization of the page on post-installation for Unix/Linux and Mac makes it easy for mac installers to miss the fact that they need to modify files before running.

The contents are listed as such

```
Install as Service on Unix/Linux
- Configuring the Script
- Installing the Script
- Installing for Mac OS X
```

This makes it seem that they are parallel methods and a mac user should skip to the "Installing for Mac OS X" section.

It would be clearer if the Mac flavor were either under the "Installing the Script" heading along with other *nix styles or if the Installing for Mac OS X section, made referred back to the `Configuring the Script` section for those who followed the navigation links directly

**Comment by luigidellaquila** [comment]
Hi @lnryan 

Good point, thank you very much for pointing it out.
I think you are referring to this page:

https://orientdb.com/docs/3.0.x/admin/Unix-Service.html

I'll review it ASAP

Of course, if you wish, you can contribute with a pull-request, the page source is public:

https://github.com/orientechnologies/orientdb-docs/blob/3.0.x/admin/Unix-Service.md

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @lnryan 

I added a note to the `Installing for Mac OS X` section that explicitly refers to configuring the script.
At next doc build, the official documentation will be automatically updated

Thanks

Luigi
