### ISSUE TITLE
OrientDB public Site all of URL links on Getting Started return error 404 ( page not found )

### ISSUE THREAD

**Issue by MironAtHome** [orientechnologies/orientdb-docs#347]
![image](https://user-images.githubusercontent.com/18360184/59557265-29bcab00-8f8a-11e9-9a6b-c80e24d40fa2.png)

**Comment by luigidellaquila** [comment]
Hi @MironAtHome 

Thank you very much for reporting, I just fixed it

Thanks

Luigi

**Comment by MironAtHome** [comment]
Hello Luigi

Looks like it's back
Here https://orientdb.org/getting-started
these links get 404 error
[cid:8193a99a-faaa-4a8d-b344-14313bec8fc8]

I checked top one, it resolves to http://orientdb.com/docs/last/gettingstarted
Apparently it expects getting resolved to this: http://orientdb.com/docs/3.0.x/gettingstarted/
but instead points to this http://orientdb.com/docs/last/Tutorial-Introduction-to-the-NoSQL-world.html
which is version 2.2.x
If you permit me, I would be looking over this for you ever week - end to keep it tidy.

Thanks,

Miron



________________________________
