### ISSUE TITLE
What is the SQL query to delete/drop a user-defined function?

### ISSUE THREAD

**Issue by pa-emmanuel** [orientechnologies/orientdb-docs#364]
I can create a function with:

CREATE FUNCTION getTest "SELECT count(*) as number FROM People WHERE age = :age" PARAMETERS [age]

But how do I delete this function with SQL.

**Comment by luigidellaquila** [comment]
Hi @pa-emmanuel 

There is no specific SQL command (yet), you can use a plain 

```
DELETE FROM OFunction WHERE name = ?
```

Thanks

Luigi

**Comment by pa-emmanuel** [comment]
> Hi @pa-emmanuel
> 
> There is no specific SQL command (yet), you can use a plain
> 
> ```
> DELETE FROM OFunction WHERE name = ?
> ```
> 
> Thanks
> 
> Luigi

Thanks Luigi.
