### ISSUE TITLE
Clusters in Match Queries 

### ISSUE THREAD

**Issue by SameerChorge94** [orientechnologies/orientdb-docs#377]
I Want to use the **clusters in Match Queries**, i.e. i have to **fetch data from** the **specified clusters only**.
It is possible in the with the SELECT Queries but not with Match Queries.

e.g. 
I have one product Vertex for which i created 2 clusters 
org1_Products and org2_Products respectively

with select query i can fetch the specific clusters data using 
```
SELECT FROM CLUSTER:org1_Products 
SELECT FROM CLUSTER:org2_Products 
```

But for Match query i checked documentation but did not get any references or syntax for passing the clusters information
```
MATCH  {class: PRODUCT, as: products }
RETURN products;
```

**And as per our project requirements we need to use the Match Query only with specified clusters.**
Kindly suggest any references or workarounds for this issue.

**Comment by luigidellaquila** [comment]
Hi @SameerChorge94 

The cluster as a MATCH target is actually supported. eg.
```
MATCH  {cluster:product, as: products }
RETURN products;

MATCH  {cluster:12, as: products }
RETURN products;
```

Thanks

Luigi

**Comment by SameerChorge94** [comment]
Thanks @luigidellaquila 
Closing issues, as with above syntax i'm able to fetch cluster specific data.
