### ISSUE TITLE
The Hello World example should be corrected

### ISSUE THREAD

**Issue by qualitesys** [orientechnologies/orientdb-docs#378]
On this page https://orientdb.com/docs/2.2.x/Extend-Server.html, the example is wrong.

``
  @Override
  public String[] getNames() {
    return new String[]{"GET|hello/* POST|hello/*"};
  }
``

should be changed to 

``
  @Override
  public String[] getNames() {
    return new String[]{"GET|hello/*","POST|hello/*"};
  }
``

Thanks

**Comment by lvca** [comment]
Thanks for the report, fixed. Changes should be online in 5 minutes.
