### ISSUE TITLE
Hello World example needs correction (send)

### ISSUE THREAD

**Issue by qualitesys** [orientechnologies/orientdb-docs#379]
On page https://orientdb.com/docs/2.2.x/Extend-Server.html the send signature is in error.

This code 

``
    iResponse.send(OHttpUtils.STATUS_OK_CODE, "OK", null, OHttpUtils.CONTENT_TEXT_PLAIN, result);
``

should be remplaced by 

``
    iResponse.send(OHttpUtils.STATUS_OK_CODE, "OK", null, result, OHttpUtils.CONTENT_TEXT_PLAIN);
``

Class 

com.orientechnologies.orient.server.network.protocol.http.OHttpResponse 

Method 

send(int iCode, String iReason, String iContentType, Object iContent, String iHeaders)

Thanks

**Comment by lvca** [comment]
Thanks for the report. Fixed on all the branches.
