### ISSUE TITLE
Update Repository

### ISSUE THREAD

**Issue by kennethpjdyer** [orientechnologies/orientdb-docs#45]
Restructure orientdb-docs to function as a standalone repository, containing all scripts and configuration files necessary to run local builds of the documentation website.  Deprecate the orientdb-manual repo.

Update to include:
- Move all docs source files into new source/ directory.
- Develop make processes for managing builds.
- Write initialization script to create relevant scripts, makefile and gitbook config files.
- Document new configuration process for orientdb-docs.
- Revise current scripts to include deprecation notice.
- Update .gitignore to blacklist deprecated scripts and custom makefile.

**Comment by santo-it** [comment]
Hi,

Trying to review all open issues and understand, for each of them, next steps.
What is the status of this? I see some commits but I am not able to understand the next steps

Can we consider this closed?

Many Thanks!

**Comment by kennethpjdyer** [comment]
Hi @santo-it , You're right, this is old.  Closing.
