### ISSUE TITLE
would be the manual hosted by this repo, hope so

### ISSUE THREAD

**Issue by zhuobao** [orientechnologies/orientdb-docs#5]
the orientdb document is "poor". Hope you can have the manual here and let users to contribute to the manual

**Comment by dbroeglin** [comment]
Hello !

No I did a copy at some point but I and some others are trying to improve it. If you have comments feel free to given them on the mailing list. From my experience, good critic is always welcome on the list.

**Comment by lvca** [comment]
Guys, you can contribute to OrientDB manual from this wiki. Take a look at: https://github.com/orientechnologies/orientdb-docs/wiki

**Comment by zhuobao** [comment]
thx, guys
