### ISSUE TITLE
[Suggestion] Resorting the summary.md

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb-docs#66]
Hi,

There is a lot of valuable information in the docs, but the way they are summarized (table of contents on the left) is a bit unwieldy and makes it harder to use the docs as a reference. I'd like to give it a go to reorder the summary to improve this. Would that be ok? And, how can I do these kinds of changes, without actually changing the docs at first, but still be able to see the changes (like in a sandbox)?

Scott

**Comment by luigidellaquila** [comment]
Hi @smolinari 

we are currently using GitBook (https://www.gitbook.com/) to generate the docs from orientdb-docs git repo. 
I think you could just fork the git repo and create your own sandbox in gitbook to see the final result.

Thanks

Luigi

**Comment by smolinari** [comment]
So, the ODB team are "ok" with me attempting to rework of the summary/ table of contents?

Scott

**Comment by luigidellaquila** [comment]
I think there is always room to improve, in particular in the documentation, so any suggestion is welcome!
Of course we will validate all the proposals

Thanks a lot!

Luigi

**Comment by smolinari** [comment]
Ok. I'll see what I can do. Thanks Luigi!

Scott

**Comment by smolinari** [comment]
@robfrank - hope you can help me here. 

When I try to create the docs in Gitbook, I can get the files in from my repo, but because everything is in the /src directory, Gitbook isn't setting up the docs correctly, like it doesn't recognize the SUMMARY.md file, because it doesn't load the book.md file (the configuration). Are you possible using some other method to load the repo into Gitbook?

Scott

**Comment by kennethpjdyer** [comment]
@smolinari

We use the node program gitbook-cli as a static site generator, but for changes make a pull request to this repo as we manage all the work here.  We tweaked the plugins list last week.  I'll update the Makefile shortly so that make install gives you what you need. If you're eager now, I believe

```sh
$ npm install gitbook-plugin-versions gitbook-plugin-collapsible-menu gitbook-plugin-addcssjs gitbook-plugin-edit-link
```

from the working directory should install what make install doesn't now.  If not, I'll test it out and have a fix pushed in a little while.

**Comment by smolinari** [comment]
@kennethpjdyer - Thanks for the help and explanation. So, if I understand correctly, the ODB documentation uses the Gitbook format (of sorts), but the format is so much different, it is impossible to import them and use them in Gitbook itself. Hmm....ok. Now I understand why it doesn't work with Gitbook. :smile: 

From a collaboration standpoint, wouldn't it be more beneficial to supporting the docs writing and correction, if the format of the files are kept in one that is standard and actually usable with Gitbook? And, when the docs are in a usable Gitbook format, the files should still work with the gitbook-cli too? 

The other thing that bothers me is all the files being in one directory. It should also be possible to structure them to be more logical and fitting to the table of contents. That makes the files easier to manage. 

So, here is a further suggestion to my original goal. In addition to reworking the SUMMARY.md, I'd like to change the format of the repo, so it works properly in Gitbook and also rework the file structure (especially so it isn't just a blob of unsorted files in Gitbook). When I am finished, it is then a matter of getting gitbook-cli to render the docs properly for the ODB site (which it should do with no problems, really). If I can accomplish that, I do believe we will be killing two birds with one stone. We'll have a much better organized source for the documentation and we'll improve the ability to collaborate on the documentation too.

What do you think?

Scott

**Comment by smolinari** [comment]
Oh, and I can write a small addition to the docs, to detail the workflow to helping with the Docs, using Gitbook. :smile: 

Scott

**Comment by kennethpjdyer** [comment]
@smolinari

Someone who knows the publication end better can correct me on this, but I don’t believe we’re really using GitBook.com anymore.  Mainly, we’re using GitBook’s production tools to update our own website at the more convenient domain: orientdb.com/docs/latest/.  (On the subject, somebody with control over that account should look into updating or removing it, as it’s months behind orientdb.com.)

Keeping the source files all in one directory is more convenient overall and works better with the toolchain.  That is, you don’t have to play guessing games with where things are hiding they only exist in one place and it makes it easier to grep the project for text.

Git itself does not handle changes in the filenames and paths very well.  There’s a move command that logs the event for commits, but internally it registers the change as your deleting the thing at Path A and adding the thing at Path B.  This introduces a huge problem for collaboration.  It means that structural changes to the website have to be copied into the repo, which is fine if you’re the only one working a section, but that disrupts the merge process for anyone working on the same chapter.

By contrast, with what we have now you can starting editing SUMMARY.md and completely restructure the website from end to end — without disrupting anyone else’s work.


— Kenneth

**Comment by smolinari** [comment]
The object of using Gitbook is so the collaborating editor/ author can see the book as it should be on the site, without having to build a VM with the Node publishing application, or even worse, wait for someone to build the changes into the live site. There needs to be a staging step in the publication process and that could be done on Gitbook free and fairly easily, of the docs would follow Gitbook's file formatting. Having "The ODB Docs Book" work on Gitbook also means more people are able to help. That should be the goal. Making it easier for people to support ODB's documentation.

Grepping for text isn't really a tool for editing, at least not for a Windows user. And grepping one directory or a set of directories isn't much of a difference either. It is a matter of adding "-r". 

Once the directory structure is fixed, there shouldn't be much changing of names or locations of files. It is a one time or rare action, with the goal to make the structure of the files more human readable. It makes it easier to work on the project outside of Gitbook too.

Personally, it doesn't really matter that much to me what happens. I am just trying to help. This situation should be mattering to the ODB team though and they should make the decision. The poor situation with the documentation is one of the biggest complaints by users. Whereas, they aren't really all that bad. There is a ton of information. It's just, IMHO, the topics are poorly organized. The first level of the table of contents (for a nav menu) is way too large. Have a look at MongoDB's docs, which constantly gets compliments. The top level is less than half the size of ODB's. I want to try and achieve something similar. 

At any rate. All I need to know is what I should do. Move forward with what I think is good, or leave it alone. But for sure, something does need to change.

Scott

**Comment by kennethpjdyer** [comment]
Not sure I follow your point on GitBook.  The build process you're describing is available already through gitbook-cli.  It works fine on Linux and Mac and is the same thing we use in prepping website updates.  Is there a reason why this wouldn't work for Windows users?

You're certainly right about the need to overhaul `SUMMARY.md` and the MongoDB docs are a good model to follow on that count.  I won't be in a position to do structural work until January at the earliest, but you're welcome to take the first run at the problem now.  Feel free to move forward there.  We'll review the pull request and make suggestions or approve it when you're ready.  

Leave the repo organization alone for now.  Position may change in the future, but for now the convenience it adds doesn't really outweigh the editorial and maintenance issues it would raise.  Id est, files shouldn't move, but a lot of them will at some point.  TOC-repo parity turns a minor edit into a significant revision, making it harder for anyone reviewing that change to see what was done.

**Comment by smolinari** [comment]
> Not sure I follow your point on GitBook. The build process you're describing is available already through gitbook-cli.

You might not be following me, because I am not concerned about the build process, but rather the collaboration process. I would think it is in ODB's best interest to make it easier for any documentation collaborators to see their work in a finished "staged" book. Gitbook can provide that process.

> You're certainly right about the need to overhaul SUMMARY.md and the MongoDB docs are a good model to follow on that count.

Glad we agree on that. :+1: 

> TOC-repo parity turns a minor edit into a significant revision, making it harder for anyone reviewing that change to see what was done.

How is that? In most cases, a minor edit is just a file change. It isn't any different than with minor edits with software in Github, and ALL software I know of has a directory structure, even ODB has one and it is quite intense. It doesn't hurt the PR reviews at all. Imagine all the ODB files in one directory. Would that simplify or complicate the collaboration on the software?

The only difference a software repo has to a book is the TOC, which wouldn't be changed for a minor edit in most cases anyway. So, from my perspective, adding a directory structure to resemble the TOC structure doesn't complicate the documentation process. I think it would simplify it, because a collaborator can find the actual file easier, without having to even refer to the TOC to find the right file name, because the filenames often differ from the TOC entry. With a directory structure, the collaborator would have only a few files to choose from, to find the right one. 

I'll go ahead and make the changes I think are necessary to the TOC and add a directory structure to my copy of the repo, since we both agree the TOC needs improvement. If the collaboration process is then such a problem or the publishing/ build process is also "broken" and unfixable, then it wouldn't be too hard to revert the files back to a single directory. 

Scott

**Comment by lvca** [comment]
Hey @smolinari, I'm looking forward for your idea about TOC. In SUMMARY.md you can create a tree of content, so there is no need to have the same structure at repository level. The problem with multiple levels (like we had in the past) is that makes hard the refactoring, because URI would change. 

Having a flat directory structure allows you to re-ensemble the TOC with no 404 for the old pages.

**Comment by smolinari** [comment]
Ok. I'll leave the files monolithic in /source and not add any directory structure. The rework of the TOC is almost done. I am having a problem with Gitbook currently though. It says the publication of the book worked, but the online preview goes to a 404. So, I have to figure out what the issue is. 

Scott

**Comment by kennethpjdyer** [comment]
@smolinari Check source/book.json for the "output" parameter.  There's a platform issue in gitbook that I've been trying to track down, where it ignores the output argument from the command-line on some platforms.  Haven't figured why or how to fix it yet.

--Kenneth

**Comment by smolinari** [comment]
Thanks. That was the problem. I removed the line and the book published. Do you possibly also know how to make the book publish with SUMMARY.md and book.json in the same directory (/source) as the rest of the book?

Scott

**Comment by kennethpjdyer** [comment]
Don't know, I can look into it.  It *should* be able to do that.  It would be nice even if it could, so we can separate source files from configs.  But, I've found gitbook to be temperamental about non-default usage.

**Comment by smolinari** [comment]
Ok. A first draft of a new TOC. 

https://smolinari.gitbooks.io/orientdb-docs/content/v/05d937300e4ada19cb35d8169149d45510b364cd/index.html

Scott

**Comment by smolinari** [comment]
Hmm...we also have another problem. All the internal links in the documentation don't work on Gitbook. 

I am going to play some more. Maybe I can get the config to read out of the /source directory.

Scott

**Comment by kennethpjdyer** [comment]
Problem may be that /source maps to the file system root rather than the document root.  Possible that gitbook ignores that, but builds links that don't.

**Comment by smolinari** [comment]
Any suggestions to get the links to work correctly? I am also still playing with the config, with little luck thus far.

Scott

**Comment by kennethpjdyer** [comment]
Does sourcing the links to "source/filename.md" help?

**Comment by smolinari** [comment]
Yeah, I'm pretty sure that would fix the internal links, but that would also mean a lot of work to change all of them. Well, unless it is possible to "find and replace" them within, say, an IDE. And then it would mean SEO and external links back to the docs would be broken too.

**Comment by smolinari** [comment]
This is disappointing.....

**Comment by smolinari** [comment]
Hmm....I've gotten Gitbook to read the summary file from the `/source` directory, but the links to the pages still have to have `/source` in them to work. What a bummer....

Scott

**Comment by smolinari** [comment]
OK! It isn't as bad as I expected. Only the links on the new introduction page are broken. The rest of the internal links are working properly. I'll fix the links in the intro, then everything should be working properly. Then I can concentrate on further rework of the summary.

Scott

**Comment by kennethpjdyer** [comment]
It's the middle of the night here, so I missed the initial point: What you're doing changes the directory path on the website from orientdb.com/latest/%.html to orientdb.com/latest/source/%.html.  

I'm reasonably sure that we shouldn't break external links if we can at all help it.  As it's very hard to get people working with other companies to fix bad links, even if they go nowhere useful.

**Comment by smolinari** [comment]
The issue is, the Gitbook.com site doesn't allow the SUMMARY.md file to be anywhere else other than in the root. Thus, with the current ODB documentation file locations, it is impossible to work with Gitbook to stage changes to see them, as they would be on the ODB site. 

https://smolinari.gitbooks.io/orientdb-docs/content/v/b9f6abdd49ebdcbd79999031116508a1f3bbeec0/

The file format I've put together is now working for Gitbook. The question is, can this file structure be publicized on ODB's site, and not break external links?

Scott

**Comment by smolinari** [comment]
Oh, wait. A possibly important note. I do have /source/SUMMARY.md being used through the config. But, all the links still must have `/source/` in them for the TOC to work and thus, all the internal links get `/source/` added to them in Gitbook.com's version. But, maybe it will work properly for ODB's build process?

Scott

**Comment by smolinari** [comment]
Maybe we could create a branch to test this on ODB?

Scott

**Comment by kennethpjdyer** [comment]
I like how you reorganized the toctree.  When I get up tomorrow I'll pull down your fork and see how it builds.  But, we need that source bit yanked out of the HTML output to avoid breaking any incoming links.

**Comment by smolinari** [comment]
Yes, I can understand how important that is. This is a bummer, if there is no other way to get Gitbook and ODB's build process to jive together (and not change all the internal links). 

Maybe it might be possible to set up some kind of staging system within ODB's site for staging documentation changes? I don't know. But for sure, it would be nice to see how updates to the docs look online as a way to QA test one's own changes.

Scott

**Comment by smolinari** [comment]
Oh, and thanks for the compliment. I like the new structure too. It still needs some more work, but I think the current basic structure is a good foundation to work off of. 

Scott

**Comment by smolinari** [comment]
@kennethpjdyer - Any status on how it builds? Does it work? Should I continue with the TOC improvements? 

I was thinking, basically, the only thing that needs to happen is to remove `/source` directory from the links in the `SUMMARY.md` file and move it, along with `book.json` to the `/source` directory and it should work. It should be possible to automate that too. So, SUMMARY.md and book.json in the root are the "master files". The ones under `/source` are only copies. 

Scott

**Comment by lvca** [comment]
@kennethpjdyer WDYT about @smolinari proposal?

**Comment by kennethpjdyer** [comment]
@smolinari Sorry it took so long to get back to you.  I played with it some last week and over the weekend, but couldn't work out a way around separating the configs and source files.  

You're right.  TOC is fine. If you update the links in SUMMARY.md and move it with book.json back into source/, it should be fine for the pull request.

**Comment by kennethpjdyer** [comment]
In terms of the main issue, reorganizing the TOC, leaving SUMMARY in source/ would work best for now.  

I've the feeling this GitBook site issue is a lot more convoluted than your fix there would address. Gulp would probably get SUMMARY working in a way that doesn't disrupt our process, but it introduces a consistency issue on internal links between the github repo and gitbook forks.  That is, the latter will need the 'source/' prefix on all internal links, but doing so would break links on the former.

I'm not sure we really need to either.  Just googling this now, but Node works on Windows, so theoretically all the Windows users need to use the same gitbook build system as the rest of us is a make.bat file to automate the npm installs and build process.

**Comment by smolinari** [comment]
Sorry, but you just lost me. Why would anyone collaborating need Node at all? Node is only necessary for the publication of the docs on the ODB site. Currently, not having SUMMARY.md under the root means the publication in Gitbook isn't possible, which also means, a collaborator can't see the book staged on a website, before it is published. 

Scott

**Comment by kennethpjdyer** [comment]
Node gives gitbook which gives a local build of the html files, in other words what shows the collaborator what it looks like in the browser and what we use here to check our work as we go.  

That's not really an unusual practice for documentation projects either.  Most Python projects have docs that use Sphinx for that functionality, the OpenStack docs used to run on Saxon B or HE, and I've seen a couple others managing it with custom XML/XSLT systems.  For any of them, you need to install the docs infrastructure to build local html.

**Comment by smolinari** [comment]
And what a PITA that is. I would imagine a goal for the collaboration on the docs, is to make it easy to help with the docs, to get more collaborators, so the docs can improve faster. Not everyone who can help is a developer or a dev ops person. In this thread, 

https://github.com/orientechnologies/orientdb/issues/4806

just about everyone complains about the docs in some way. 

It wouldn't be hard at all to do what I am asking for on the ODB publication side. And I'll even write a "how to" with directions on getting up and running to work on the docs with Gitbook. That way, if someone says they'd like to help with the docs, you can point them straight.....to the docs. :smile: 

Scott

**Comment by lvca** [comment]
Hey guys, if the problem is having everything in the same folder we can move everything in source. Am I wrong? If this would help document writer why not?

**Comment by smolinari** [comment]
Hi @lvca,

The problem is that everything is in the `/source` folder. Unfortunately, Gitbook won't publish the book, with `SUMMARY.md` and `book.json`missing from the root directory. Thus, there are two extra steps needed to get the ODB site publishing to work and still allow Gitbook to work, so collaborators can stage their work. Like my work here. :smile: 

https://smolinari.gitbooks.io/orientdb-docs/content/v/b9f6abdd49ebdcbd79999031116508a1f3bbeec0/

This was only possible by reworking the `SUMMARY.md` file and moving it and the `book.json` file into the root directory, which seems to break the ODB publication process. I don't understand that either, because gitbook-cli should work with the same file structure that Gitbook uses.

At any rate, the two extra steps needed are:

1. Copy the `SUMMARY.md` and `book.json` files to the `/source` directory.
2. Remove the instances of `/source` out of the `SUMMARY.md` file.

These steps can theoretically be done with [two Gulp tasks](https://github.com/orientechnologies/orientdb-docs/issues/66#issuecomment-157154292), before the publication process runs.

Scott

**Comment by kennethpjdyer** [comment]
@smolinari My guess is that GitBook is using gitbook-cli, but they're using their own script instead of our Makefile tells them to do, so it trips over itself trying to find SUMMARY in the project root, instead of running over source.  

GitBook also parses SUMMARY links the same way it does internal links, it just uses them differently.  So, I'm pretty sure your Gulp thing will fix SUMMARY but break all the internal links throughout the docs.  Easiest way to get both is @lvca's point.  We move the source files back into the project root.  It won't be pretty or neat, but all the backend stuff on both sides will work as before.

I don't want to get in the way of anybody's commits, so I'll wait till Friday night or Saturday to do all that.

**Comment by smolinari** [comment]
Gitbook.com doesn't use the makefile. I just tested it. The loading of plugins and publication process seem to be controlled purely over `book.json` and the reason why that file needs to be in the root too.

I also don't understand, how changing the links in the `SUMMARY.md` file break all the other links in the other files? The Gulp task suggested only changes the `SUMMARY.md` file, so it can work under the `/source` directory.

The reluctance to make this happen seems also strange to me. It doesn't seem at all hard to get the ODB publication process and the Gitbook publication process to jive together, in the hopes that more people can collaborate easier on the docs using Gitbook.com and Github.  

Scott

**Comment by lvca** [comment]
Ok guys, so to resume the solution we're going to move everything outside the source folder and we'll remove it. So the structure will be flat like it was months ago. @kennethpjdyer can you do that?

**Comment by smolinari** [comment]
Ah, ok. I misunderstood you earlier Luca. Can I play with that "root only" scenario with Gitbook? It should work. Then I can offer up a PR with the changes in the repo. 

Scott

**Comment by lvca** [comment]
Hey @smolinari if you can do that it would be great. I've just added a new entry to the summary a few days ago: the new console command "list servers".

**Comment by kennethpjdyer** [comment]
@lvca That's no problem.  I'll move everything around this weekend so we don't step on anybody with the commit.  

It should work fine with GitBook since it's what we were using before.

**Comment by lvca** [comment]
You shouldn't wait for the weekend, most of users use GitHub web interface. I'd say first is better. Or maybe @smolinari is faster.

**Comment by kennethpjdyer** [comment]
Okay, I thought that was the quiet time for the repo.  I'll do it now then.

**Comment by smolinari** [comment]
That works great now. Thanks @kennethpjdyer. I've reworked in my changes to SUMMARY.md. Here is the start. 

https://smolinari.gitbooks.io/orientdb-documentation/content/v/9ad3907d6d773aef4f6e8e977dd3e9792876c333/

If @lvca you are happy with this direction, I'll continue to move forward with my reworking of the SUMMARY.md. 

Would you have any issue with a bit of reformatting of the docs design (minimal things like adding <hr>s in certain places and improvement/ standardization of "See Also:" sections, etc.), some link changing in the docs and some grammar corrections, when I run into them?

Scott

**Comment by lvca** [comment]
@smolinari are you kidding? Your work is great, please don't stop :-)

**Comment by smolinari** [comment]
Great and thanks. :smile: I'll close this issue then. If I run into any further troubles or have questions, I'll start a new issue.

Scott
