### ISSUE TITLE
Docs Refactor Progress

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb-docs#74]
Hi,

Opening an issue, so the progress can be folllowed.

I am also not sure how you'd like to have the changes worked into the docs @lvca. All merged, once I am finished? Or, as I go along. My goal is to go chapter by chapter. Currently "Getting Started" is finished.

https://smolinari.gitbooks.io/orientdb-documentation/content/v/7038a670d140a9be5a86364bca2b61bca61f54fc/

Let me know how you'd like me to make PRs. 

Scott

**Comment by smolinari** [comment]
Ok. I'll move upgrade. I wasn't quite happy with it being under "Getting Started" either. I'll move it, then create the PR.

Scott

**Comment by smolinari** [comment]
I noticed some of the things I had pushed under "Contribute to OrientDB" were pushed a level higher into the top level.

![image](https://cloud.githubusercontent.com/assets/3314957/11264303/e02b2af8-8e92-11e5-9a31-eab03356c5c4.png)

Ok.  I can understand the want to have "Enterprise Edition" out in the open.

Though, I'd like to do this.

![image](https://cloud.githubusercontent.com/assets/3314957/11264461/ebdf7a9c-8e93-11e5-9741-6d574c7e1c39.png)

I moved "Server" and "Plugins" back into "Internals" and moved "Internals" up. I think that looks better and is more logical from both a "I want to learn OrientDB" and a "This is what you should see about OriendDB" perspective.

Scott

**Comment by kennethpjdyer** [comment]
@smolinari  Not sure what issue you're doing this under now, so I'm putting it here as a general thing.  I removed your Run Studio instance from Getting Started, I'll have a new Studio tutorial page written in a week or two to replace it.

Need to watch for double entries on `SUMMARY.md`.  GitBook only parses the first instance and ignores the rest and anything under the rest.  In this case, there were two calls to `Home-page.md`, the second with all the subpages didn't render and that broke all the links to those subpages.

I don't think we need a full guide to Studio in Getting Started, hence the new material.

**Comment by smolinari** [comment]
Thanks Kenneth. I didn't know that about the parsing. 

I also have one other suggestion. I think "Console" could be changed to "Administration". Theoretically "ETL" and "Scaling" could then be put under that section and it would really clean up the starting index. 

What do you think?

Scott

**Comment by kennethpjdyer** [comment]
That's alright.  I didn't know about it either until I started tracking errors.  Also something to keep an eye out for: GitBook only throws an error when you drop a file from the build that other files link to.  Files in the repo that we don't link to otherwise, it ignores.  Example: The overwrite here with `Home-page.md` actually dropped eleven files from the build.  But, it only threw one error, due to a link elsewhere to `Studio-Auditing.md`.

Basic Run the Studio page up now with the inclusion bit added to `SUMMARY`.  I'll flesh it out more after I get through the Console Commands.

Administration or Management works.  There's probably more that could be folded into that chapter.

**Comment by santo-it** [comment]
Hi,

I think this is old and can be closed now?

We can track bugs, enhancements and refactor tasks using the corresponding labels:

- All open bugs: https://github.com/orientechnologies/orientdb-docs/issues?q=is%3Aissue+is%3Aopen+label%3Abug

- All open enhancements: https://github.com/orientechnologies/orientdb-docs/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement

- All open refactor tasks: https://github.com/orientechnologies/orientdb-docs/issues?q=is%3Aissue+is%3Aopen+label%3Arefactor

Prioritization is done in the following board:
https://github.com/orientechnologies/orientdb-docs/projects/1

Let me know if you are okay in closing this

Thanks,
