### ISSUE TITLE
Minimum Java version requirement needs an update

### ISSUE THREAD

**Issue by shturec** [orientechnologies/orientdb-docs#85]
The documentation (labeled "last" on your site as of the time of this writing) quotes the following:
"OrientDB requires Java, version 1.6 or higher." (http://orientdb.com/docs/last/Tutorial-Installation.html)
My observation is that there is already Java 1.8 specific code that requires Java 8 as minimum requirement.
I stumbled upon this with a simple example servlet deployed in Tomcat that uses the jdbc driver to connect to orient db.
Initially, it was compiled with Java 7 and failed, complaining for a missing method in Map (putIfAbsent). As soon as I rebuilt with Java 8 the sample started working as expected.

**Comment by smolinari** [comment]
I've corrected the docs in this PR. https://github.com/orientechnologies/orientdb-docs/pull/91

Scott

**Comment by santo-it** [comment]
Hi,

Thanks for opening this issue, and thanks for the PR Scott
Current page (http://orientdb.com/docs/master/Tutorial-Installation.html#prerequisites) cites java 1.7 or higher, as a requirement

The use of java 8 code (Map.putIfAbsent) was a bug that has been fixed. I think we can close this issue now. Please feel free to reopen if needed

Many Thanks,
