### ISSUE TITLE
Proofreading Spatial-Module.md

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb-docs#88]
This sounds like a really cool feature.

However, I have two possible issues with this doc page though.
________
- Shouldn't it be a standard in the docs, that all SQL be full-caps?

Like 

`insert into TestLineSTring set name = 'Test1' , location = St_GeomFromText("LINESTRING(0 0, 3 3)")`

should be 

`INSERT INTO TestLineSTring SET name = 'Test1' , location = St_GeomFromText("LINESTRING(0 0, 3 3)")`
________

 
- The function explanations are a bit confusing. 

![image](https://cloud.githubusercontent.com/assets/3314957/11708558/93f189b4-9f10-11e5-86b0-e160ea858ea6.png)

It took me a moment to realize, the information under the example is the result.

Wouldn't it be better to just say "Result"?

https://smolinari.gitbooks.io/orientdb-documentation/content/v/57961cdfcdaf42e0bbb9d8517c89977a578befae/Spatial-Module.html

I've made the changes. Hope that was also correct.

Scott

**Comment by kennethpjdyer** [comment]
You're right.  Revisions are already under way to fix SQL syntax, console displays, and various markup and consistency issues throughout the text.   That's just a page that hasn't been covered yet.  

New style deals with the 'results' problem.

**Comment by smolinari** [comment]
Ah. Hmm... ok. I didn't know that was happening and didn't know things were being "standardized". That is cool! :+1: 

How about a "docs standards and procedures" page in the contribution section? So, anyone contributing can follow them?

Scott

**Comment by smolinari** [comment]
Oh, can we also have the rule I started, that if someone proofread a page (and set it to the standards), they add an html comment like follows. 

`<!-- proofread 2015-12-10 XXX -->`

where "XXX" are the initials of the person who did the proofreading? That way, if the data is fairly up-to-date, then there aren't people doing unnecessary double work.

Scott

**Comment by lvca** [comment]
+1 for the proofread idea

**Comment by smolinari** [comment]
Closing this. I've started a new topic about standardization and procedures for the docs. https://github.com/orientechnologies/orientdb-docs/issues/90

Scott
