### ISSUE TITLE
Search sticks across sessions and breaks the navigation, when returning to the docs site

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb-docs#93]
Not sure why.

I have two PRs waiting. I'd like those to be merged, before I can start to troubleshoot. Maybe the merging will even fix the problem? 

Scott

**Comment by smolinari** [comment]
The PRs are now merged. Thanks @lvca. How long does it take for the changes to propagate to the live docs on the ODB website?

Scott

**Comment by smolinari** [comment]
Hahaha! This issue has nothing to do with the content it seems.

I had used the search yesterday, and it seems the search "sticks", meaning, if you come back to the docs later, the search is still there and messes up the navigation. 

Scott

**Comment by smolinari** [comment]
Steps to replicate. 

1. go to the docs and use the search for transactions.
2. close the browser window.
3. go back to the docs.
4. click into one of the sections in the navigation

Expected. 

No search values in the search. Navigation works normally.

What actually happens?

Search value is still there (upper left) and messes up the navigation (some of the sections are missing).

Scott

**Comment by santo-it** [comment]
Hi @smolinari ,

Thanks for opening this issue. Just wondering, are you still able to repeat this with latest versions of the doc?

Thanks,

**Comment by smolinari** [comment]
Seems like the issue I reported is no longer an issue. I'll close. 

Scott
