### ISSUE TITLE
Anchors/ Links in methods page aren't working.

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb-docs#98]
http://orientdb.com/docs/2.1/SQL-Methods.html

None of the links/ anchors to the different methods are working.

Scott

**Comment by luigidellaquila** [comment]
Hi @smolinari 

Thanks for reporting, it seems there is an additional `-` sign in the anchors, maybe it's due to GitBook formatting, because the links seem to work fine in GitHub...

Thanks

Luigi

**Comment by smolinari** [comment]
Just wondering if it can be correct and how. If I can do it in the text, I'd do it. I am just not sure if the problem is in the text or with the gitbook app. 

Scott

**Comment by luigidellaquila** [comment]
It's hard to say, my guess is that the problem is in the dotted list or in the dot before the method name, but it's only a guess, I should try it to make sure that the problem is not somewhere else...

Luigi

**Comment by smolinari** [comment]
The other pages with such tables of anchor links work properly. Like the methods page. I haven't looked, but maybe it is possible to see a difference?

Scott

**Comment by smolinari** [comment]
Hey @robfrank - The links still don't work! Or is the fix coming?

Scott

**Comment by robfrank** [comment]
Sorry, I checked on 2.2 and last

**Comment by smolinari** [comment]
Hmm...no. I am sorry. I went to the link at the top of the thread and it goes to 2.1. LOL! 2.2 seems to work, yes.

But I found another problem. If you are in 2.2 and click on "Version Last" in the pulldown on the left, it goes to version 1.7???

Scott

**Comment by robfrank** [comment]
@smolinari , the version selection is bugged, but it'a a gitbook pulging, I can't do more on it.

**Comment by smolinari** [comment]
Maybe it is just a config problem with each of the book's book.json?

https://github.com/GitbookIO/plugin-versions

Scott

**Comment by robfrank** [comment]
I fixed 2.1, 2.2., master (last/3.0.x) . If you still see wrong links, please refresh your browser's cache.

**Comment by smolinari** [comment]
Cool! Looks like you fixed the versions menu too. :sunglasses: :+1: 

Scott
